# Generated by Django 4.2.26 on 2025-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item name')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('quantity_in_pack', models.IntegerField(verbose_name='Quantity in pack')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
            ],
        ),
    ]
